name: arbify
description: >
  A package providing support for internationalizing
  Flutter applications using intl package with Arbify.
version: 0.2.0
homepage: https://github.com/Arbify/arbify_flutter

false_secrets:
  - example/.secret.arbify

environment:
  sdk: ">=2.14.4 <4.0.0"

dependencies:
  args: ^2.4.2
  dio: ^5.4.2
  flutter:
    sdk: flutter
  intl: ^0.18.0
  intl_utils: ">=2.8.7"
  path: ">=1.9.0"
  petitparser: ">=6.0.2"
  universal_io: ">=2.2.2"
  yaml: ">=3.1.2"

dev_dependencies:
  build_runner: ^2.4.8
  lint: ">=2.3.0"
  mockito: ">=5.4.4"
  test: ">=1.25.2"
