name: arbify
description: >
  A package providing support for internationalizing
  Flutter applications using intl package with Arbify.
version: 0.2.0
homepage: https://github.com/Arbify/arbify_flutter

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  args: ">=2.0.0 <3.0.0"
  dio: ">=4.0.0 <4.1.0"
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <0.18.0"
  intl_utils: ">=2.6.0 <3.0.0"
  path: ">=1.8.0 <2.0.0"
  petitparser: ">=4.0.2 <5.0.0"
  universal_io: ">=2.0.3 <3.0.0"
  yaml: ">=3.1.0 <4.0.0"

dev_dependencies:
  build_runner: ">2.0.0 <3.0.0"
  lint: ">=1.5.3 <2.0.0"
  mockito: ">=5.0.3 <5.1.0"
  test: ">=1.16.8 <2.0.0"
